### ISSUE TITLE
section lacks heading

### ISSUE THREAD

**Issue by r20222** [RickVellingaa/the-startup-responsive-interactieve-website#5]
https://github.com/RickVellingaa/the-startup-responsive-interactieve-website/blob/198d9cba0ca10306164f57c80477c51ac1324816/index.html#L68

Ik kreeg het volgende uit de html validator:

Section lacks heading. Consider using h2-h6 elements to [add identifying headings to all sections](https://www.w3.org/wiki/HTML/Usage/Headings/Missing), or else use a div element instead for any cases where no heading is needed.

From line 68, column 9; to line 68, column 17

Misschien is het handig  om het in een div te veranderen. 

Mooie website navigation! ga zo door!

**Comment by RickVellingaa** [comment]
div van gemaakt, fixed!
